version: "3.3"
services:
  tauc-tr-143:
    image: 'nginx:latest'
    restart: "unless-stopped"
    ports:
      - '84240:80'
    volumes:
      - ./download-files:/usr/share/nginx/html/downloads:ro
      - ./site-config:/etc/nginx/conf.d
